services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      DJANGO_DEBUG: "1"

      POSTGRES_DB: beauty_salon
      POSTGRES_USER: beauty
      POSTGRES_PASSWORD: beauty
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"

      PYTHONUTF8: "1"
      PYTHONUNBUFFERED: "1"
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -lc "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: beauty_salon
      POSTGRES_USER: beauty
      POSTGRES_PASSWORD: beauty
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beauty -d beauty_salon"]
      interval: 5s
      timeout: 3s
      retries: 20
    # порт наружу не обязателен. Если нужно подключаться с хоста — раскомментируй:
    # ports:
    #   - "5432:5432"

volumes:
  postgres_data:
